name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # or another version

      - name: Install Android SDK
        run: |
          echo "y" | sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Build with Gradle
        run: ./gradlew assembleDebug  # or the appropriate Gradle command
